CALLBACK_BUTTON1_10 = "callback_button1_10"
CALLBACK_BUTTON2_20 = "callback_button2_20"
CALLBACK_BUTTON3_30 = "callback_button3_30"
CALLBACK_BUTTON4_40 = "callback_button4_40"
CALLBACK_BUTTON5_50 = "callback_button5_50"
CALLBACK_BUTTON6_60 = "callback_button6_60"
CALLBACK_BUTTON7_70 = "callback_button7_70"
CALLBACK_BUTTON8_80 = "callback_button8_80"
CALLBACK_BUTTON9_90 = "callback_button9_90"
CALLBACK_BUTTON10_100 = "callback_button10_100"
CALLBACK_BUTTON11_SWITCH = "callback_button11_switch"
CALLBACK_BUTTON12_INCREASE = "callback_button12_increase"
CALLBACK_BUTTON13_DECREASE = "callback_button13_decrease"
CALLBACK_BUTTON14_SOUND = "callback_button14_sound"

CALLBACK_BUTTON20_SCREEN = "callback_button20_screen"
CALLBACK_BUTTON21_SCREEN_SAVER = "callback_button21_screen_saver"
# CALLBACK_BUTTON22_MONITOR_ON = "callback_button22_monitor_on"
CALLBACK_BUTTON23_MONITOR_OFF = "callback_button23_monitor_off"
CALLBACK_BUTTON24_MONITOR2_ON = "callback_button24_monitor2_on"
CALLBACK_BUTTON25_MONITOR2_OFF = "callback_button25_monitor2_off"
CALLBACK_BUTTON26_MONITORS_ON = "callback_button26_monitors_on"
CALLBACK_BUTTON27_MONITORS_OFF = "callback_button27_monitors_off"

CALLBACK_BUTTON40_SYSTEM = "callback_button40_system"
CALLBACK_BUTTON41_SYSTEM_SHUTDOWN = "callback_button41_system_shutdown"
CALLBACK_BUTTON42_SYSTEM_REBOOT = "callback_button42_system_reboot"
CALLBACK_BUTTON43_SYSTEM_LOCKWORKSTATION = "callback_button43_system_lockworkstation"
CALLBACK_BUTTON44_SYSTEM_TSDISCON = "callback_button44_system_tsdiscon"

CALLBACK_BUTTON60_MPC = "callback_button60_mpc"
CALLBACK_BUTTON61_MPC_FULL = "callback_button61_mpc_full"
CALLBACK_BUTTON62_MPC_PLAY = "callback_button62_mpc_play"
CALLBACK_BUTTON63_MPC_FORWARD_SMALL = "callback_button63_mpc_small"
CALLBACK_BUTTON64_MPC_FORWARD_MEDIUM = "callback_button64_mpc_medium"
CALLBACK_BUTTON65_MPC_FORWARD_LARGE = "callback_button65_mpc_large"
CALLBACK_BUTTON66_MPC_BACKWARD_SMALL = "callback_button66_mpc_small"
CALLBACK_BUTTON67_MPC_BACKWARD_MEDIUM = "callback_button67_mpc_medium"
CALLBACK_BUTTON68_MPC_BACKWARD_LARGE = "callback_button68_mpc_large"

TITLES = {
	CALLBACK_BUTTON1_10: "10%",
	CALLBACK_BUTTON2_20: "20%",
	CALLBACK_BUTTON3_30: "30%",
	CALLBACK_BUTTON4_40: "40%",
	CALLBACK_BUTTON5_50: "50%",
	CALLBACK_BUTTON6_60: "60%",
	CALLBACK_BUTTON7_70: "70%",
	CALLBACK_BUTTON8_80: "80%",
	CALLBACK_BUTTON9_90: "90%",
	CALLBACK_BUTTON10_100: "100%",
	CALLBACK_BUTTON11_SWITCH: "Вкл/выкл звук",
	CALLBACK_BUTTON12_INCREASE: "+",
	CALLBACK_BUTTON13_DECREASE: "-",
	CALLBACK_BUTTON14_SOUND: "Звук",

	CALLBACK_BUTTON20_SCREEN: "Экран",
	CALLBACK_BUTTON21_SCREEN_SAVER: "Включить заставку",
	# CALLBACK_BUTTON22_MONITOR_ON: "Включить монитор",
	CALLBACK_BUTTON23_MONITOR_OFF: "Выключить монитор",
	CALLBACK_BUTTON24_MONITOR2_ON: "Включить монитор 2",
	CALLBACK_BUTTON25_MONITOR2_OFF: "Выключить монитор 2",
	CALLBACK_BUTTON26_MONITORS_ON: "Включить все экраны",
	CALLBACK_BUTTON27_MONITORS_OFF: "Выключить все экраны",

	CALLBACK_BUTTON40_SYSTEM: "Система",
	CALLBACK_BUTTON41_SYSTEM_SHUTDOWN: "Выключить компьютер",
	CALLBACK_BUTTON42_SYSTEM_REBOOT: "Перезагрузить компьютер",
	CALLBACK_BUTTON43_SYSTEM_LOCKWORKSTATION: "Блокировать",
	CALLBACK_BUTTON44_SYSTEM_TSDISCON: "Смена пользователя",

	CALLBACK_BUTTON60_MPC: "MPC",
	CALLBACK_BUTTON61_MPC_FULL: "Media Player Classic",
	CALLBACK_BUTTON62_MPC_PLAY: "Пауза/воспроизведение",
	CALLBACK_BUTTON63_MPC_FORWARD_SMALL: ">",
	CALLBACK_BUTTON64_MPC_FORWARD_MEDIUM: ">>",
	CALLBACK_BUTTON65_MPC_FORWARD_LARGE: ">>>",
	CALLBACK_BUTTON66_MPC_BACKWARD_SMALL: "<",
	CALLBACK_BUTTON67_MPC_BACKWARD_MEDIUM: "<<",
	CALLBACK_BUTTON68_MPC_BACKWARD_LARGE: "<<<",

}